StoreProject/Models/Domain/Category.cs
namespace StoreProject.Models.Domain
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }

        public DateTime CreationDate { get; set; }
        public ICollection<Product> Products { get; set; }
    }
}

StoreProject/Models/Domain/Product.cs
namespace StoreProject.Models.Domain
{
    public class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }

        public string FeaturedImageUrl { get; set; }
        public DateTime CreationDate { get; set; }
        public bool Visible { get; set; }
        public ICollection <Category> Categories { get; set; }
    }
}

StoreProject/Models/ErrorViewModel.cs
namespace StoreProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StoreProject/Models/ViewModels/AddCategoryRequest.cs
namespace StoreProject.Models.ViewModels
{
    public class AddCategoryRequest
    {
        public string Name { get; set; }

        public string Description { get; set; }
    }
}

StoreProject/Models/ViewModels/AddProductRequest.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using StoreProject.Models.Domain;

namespace StoreProject.Models.ViewModels
{
    public class AddProductRequest
    {
        public string ProductName { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int Stock { get; set; }

        public string FeaturedImageUrl { get; set; }
        public DateTime CreationDate { get; set; }
        public bool Visible { get; set; }

        public IEnumerable<SelectListItem> Categories { get; set; }
        public string[] SelectedCategories { get; set; } = Array.Empty<string>();
    }
}

StoreProject/Models/ViewModels/EditCategoryRequest.cs
namespace StoreProject.Models.ViewModels
{
    public class EditCategoryRequest
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }

    }
}

StoreProject/Controllers/AdminCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StoreProject.Data;
using StoreProject.Models;
using StoreProject.Models.Domain;
using StoreProject.Models.ViewModels;
using StoreProject.Repositories;

namespace StoreProject.Controllers
{
    public class AdminCategoryController : Controller
    {
        private ICategoryRepository categoryRepository;
        public AdminCategoryController(ICategoryRepository categoryRepository)
        {
            this.categoryRepository = categoryRepository;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> SaveCategory(AddCategoryRequest addCategoryRequest)
        {

            var category = new Category
            {
                CategoryName = addCategoryRequest.Name,
                CategoryDescription = addCategoryRequest.Description,

                CreationDate = DateTime.Now,
            };

            await categoryRepository.AddAsync(category);
            return RedirectToAction("List");
        }

        public async Task<IActionResult> List()
        {
            var categories = await categoryRepository.GetAllAsync();
            return View(categories);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var category = await categoryRepository.GetAsync(id);

            if (category != null)
            {
                var editCategoryRequest = new EditCategoryRequest
                {
                    CategoryId = category.CategoryId,
                    CategoryName = category.CategoryName,
                    CategoryDescription = category.CategoryDescription

                };

                return View(editCategoryRequest);
            }

            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditCategoryRequest editCategoryRequest)
        {

            var category = new Category
            {
                CategoryId = editCategoryRequest.CategoryId,
                CategoryName = editCategoryRequest.CategoryName,
                CategoryDescription = editCategoryRequest.CategoryDescription

            };

            var existingCategory = await categoryRepository.UpdateAsync(category);

            if (existingCategory != null)
            {
                return RedirectToAction("List");
            }

            else
            {
                return RedirectToAction("Edit", new { id = category.CategoryId });
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var deletedCategory = await categoryRepository.DeleteAsync(id);

            if (deletedCategory != null) 
            {
                return RedirectToAction("List");
            }

            return RedirectToAction("Edit", new { id = id });
        }
    }
}

StoreProject/Controllers/AdminProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StoreProject.Models.Domain;
using StoreProject.Models.ViewModels;
using StoreProject.Repositories;

namespace StoreProject.Controllers
{
    public class AdminProductController : Controller
    {
        private readonly ICategoryRepository categoryRepository;
        private readonly IProductRepository productRepository;

        public AdminProductController(ICategoryRepository categoryRepository, IProductRepository productRepository)
        {
            this.categoryRepository = categoryRepository;
            this.productRepository = productRepository;
        }

        public async Task<IActionResult> List()
        {
            var products = await productRepository.GetAllAsync();
            return View(products);
        }

        public async Task<IActionResult> Add()
        {
            var categories = await categoryRepository.GetAllAsync();

            var model = new AddProductRequest
            {
                Categories = categories.Select(x => new SelectListItem { Text = x.CategoryName, Value = x.CategoryId.ToString() })
            };
            return View(model);
        }

        [HttpPost]
        [ActionName("Add")]
        public async Task<IActionResult> SaveProduct(AddProductRequest addProductRequest)
        {

            var product = new Product
            {
                ProductName = addProductRequest.ProductName,
                Description = addProductRequest.Description,
                Price = addProductRequest.Price,
                Stock = addProductRequest.Stock,
                FeaturedImageUrl = addProductRequest.FeaturedImageUrl,
                Visible = addProductRequest.Visible,

                CreationDate = DateTime.Now,
            };

            var selectedCategories = new List<Category>();
            foreach (var selectedCategoryId in addProductRequest.SelectedCategories)
            {
                var selectedCategoryAsInt = int.Parse(selectedCategoryId);
                var existingCategory = await categoryRepository.GetAsync(selectedCategoryAsInt);
                if (existingCategory != null) 
                {
                   selectedCategories.Add(existingCategory); 
                }
            }

            product.Categories = selectedCategories;
            await productRepository.AddAsync(product);
            return RedirectToAction("Add");
        }
    }
}

StoreProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StoreProject.Models;
using System.Diagnostics;

namespace StoreProject.Controllers
{

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StoreProject/Views/AdminCategory/Add.cshtml
 @model StoreProject.Models.ViewModels.AddCategoryRequest

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Add new Category</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-control" id="name" asp-for="Name" />
        </div>

        <div class="mb-3">
            <label class="form-label">Description</label>
            <input type="text" class="form-control" id="description" asp-for="Description" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>

StoreProject/Views/AdminCategory/Edit.cshtml
@model StoreProject.Models.ViewModels.EditCategoryRequest


<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Edit Category</h1>
    </div>
</div>

<div class="container py-5">
    @if(Model != null)
    {
        <form method="post">
            <div class="mb-3">
                <label class="form-label">ID</label>
                <input type="text" id="id" class="form-control" asp-for="CategoryId" readonly />
            </div>

            <div class="mb-3">
                <label class="form-label">Name</label>
                <input type="text" id="name" class="form-control" asp-for="CategoryName" />
            </div>

            <div class="mb-3">
                <label class="form-label">Description</label>
                <input type="text" id="description" class="form-control" asp-for="CategoryDescription" />
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-dark">Update</button>
            </div>
        </form>
    }
    else
    {
        <p>No category found!</p>
    }

</div>

StoreProject/Views/AdminCategory/List.cshtml
@model List<StoreProject.Models.Domain.Category>

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Show All Categories</h1>
    </div>
</div>

<div class="container py-5">
    @if (Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var category in Model)
                {
                    <tr>
                        <td>@category.CategoryId</td>
                        <td>@category.CategoryName</td>
                        <td>@category.CategoryDescription</td>                                
                        <td>
                            <a class="btn btn-dark" asp-area="" asp-controller="AdminCategory" asp-action="Edit" asp-route-id="@category.CategoryId">Edit</a> |
                             <a class="btn btn-danger" asp-area="" asp-controller="AdminCategory" asp-action="Delete" asp-route-id="@category.CategoryId">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    else
    {
        <p>No categories found!</p>
    }
</div>

StoreProject/Views/AdminProduct/Add.cshtml
 @model StoreProject.Models.ViewModels.AddProductRequest


<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Add new Product</h1>
    </div>
</div>

<div class="container py-5">
    <form method="post">
        <div class="mb-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-control" id="name" asp-for="ProductName" />
        </div>

        <div class="mb-3">
            <label class="form-label">Description</label>
            <textarea class="form-control" id="description" asp-for="Description"></textarea>
        </div>

        <div class="mb-3">
            <label class="form-label">Price</label>
            <input type="number" class="form-control" id="price" asp-for="Price" />
        </div>

        <div class="mb-3">
            <label class="form-label">Stock</label>
            <input type="number" class="form-control" id="stock" asp-for="Stock" />
        </div>

        <div class="mb-3">
            <label class="form-label">Featured Image Url</label>
            <input type="text" class="form-control" id="featuredImageUrl" asp-for="FeaturedImageUrl" />
        </div>


        <div class="mb-3">
            <label class="form-label">Categories</label>

            <select class="form-select dropCategories" asp-items="@Model.Categories" asp-for="SelectedCategories" multiple="multiple">
                <option selected disabled>Selecciona una categoría</option>
            </select>
        </div>

        <div class="form-check mb-3">
            <input class="form-check-input" type="checkbox" id="visible" asp-for="Visible">
            <label class="form-check-label">
                Visible
            </label>
        </div>

        <select class="js-example-basic-multiple" name="states[]" multiple="multiple">
            <option value="AL">Alabama</option>
            ...
            <option value="WY">Wyoming</option>
        </select>

        <select class="js-example-basic-multiple" name="states[]" multiple>
            <option value="AL">Alabama</option>
            ...
            <option value="WY">Wyoming</option>
        </select>
        <div class="mb-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>
<script src="~/js/jquery_3.5.1_jquery.min.js"></script>

<script src="~/js/select2.min.js"></script>

<script>
    $(document).ready(function () {
        $('.js-example-basic-multiple').select2();
    });
</script>

StoreProject/Views/AdminProduct/List.cshtml
@model List<StoreProject.Models.Domain.Product>

<div class="bg-secondary bg-opacity-10 py-2">
    <div class="container">
        <h1>Show All Categories</h1>
    </div>
</div>

<div class="container py-5">
    @if (Model != null && Model.Any())
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Stock</th>
                    <th>Actions</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var product in Model)
                {
                    <tr>
                        <td>@product.ProductId</td>
                        <td>@product.ProductName</td>
                        <td>@product.Description</td>
                        <td>@product.Price</td>
                        <td>@product.Stock</td>

                        <td>
                            <a class="btn btn-dark" asp-area="" asp-controller="AdminCategory" asp-action="Edit" asp-route-id="@product.ProductId">Edit</a> |
                            <a class="btn btn-danger" asp-area="" asp-controller="AdminCategory" asp-action="Delete" asp-route-id="@product.ProductId">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    else
    {
        <p>No categories found!</p>
    }
</div>

StoreProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StoreProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StoreProject</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StoreProject.styles.css" asp-append-version="true" />
    <link href="~/css/select2.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StoreProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Admin
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="AdminCategory" asp-action="Add">Add Category</a>
                                <a class="dropdown-item" asp-area="" asp-controller="AdminCategory" asp-action="List">Show Categories</a>
                                <a class="dropdown-item" asp-area="" asp-controller="AdminProduct" asp-action="Add">Add Products</a>
                                <a class="dropdown-item" asp-area="" asp-controller="AdminProduct" asp-action="List">Show Products</a>

                            </div>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - StoreProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   <script src="~/lib/jquery/dist/jquery.min.js"></script>
   <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>